from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER


def generate_session_pdf(session) -> bytes:
    """Generate a PDF report for a diagnosis session. Returns raw PDF bytes."""
    patient_code = session.patient.patient_code if session.patient else f"PT-{session.patient_id}"
    result_json = session.result_json or {}

    recommendations = result_json.get("recommendations", [])
    if session.agent_type == "voice":
        transcript_or_findings = session.input_summary or ""
    elif session.agent_type == "imaging":
        transcript_or_findings = result_json.get("findings", "")
    elif session.agent_type == "ocr":
        transcript_or_findings = result_json.get("summary", "")
    else:
        transcript_or_findings = ""

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        alignment=TA_CENTER,
        spaceAfter=20
    )
    heading_style = styles['Heading2']
    normal_style = styles['Normal']

    story = []

    story.append(Paragraph("NEURAMED CLINICAL REPORT", title_style))
    story.append(Spacer(1, 12))

    created_at_str = session.created_at.strftime("%Y-%m-%d %H:%M:%S") if session.created_at else "Unknown"
    story.append(Paragraph(f"<b>Patient:</b> {patient_code}", normal_style))
    story.append(Paragraph(f"<b>Date:</b> {created_at_str}", normal_style))
    story.append(Paragraph(f"<b>Agent Type:</b> {session.agent_type.upper() if session.agent_type else 'Unknown'}", normal_style))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Conditions Detected:", heading_style))
    if session.conditions_detected:
        for condition in session.conditions_detected:
            story.append(Paragraph(f"&bull; {condition}", normal_style))
    else:
        story.append(Paragraph("None detected", normal_style))
    story.append(Spacer(1, 12))

    conf_pct = round((session.confidence_score or 0) * 100, 1)
    story.append(Paragraph(f"<b>Confidence Score:</b> {conf_pct}%", normal_style))
    story.append(Paragraph(f"<b>Urgency Level:</b> {session.urgency_level.upper() if session.urgency_level else 'UNKNOWN'}", normal_style))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Recommendations:", heading_style))
    if recommendations:
        for i, rec in enumerate(recommendations, 1):
            story.append(Paragraph(f"{i}. {rec}", normal_style))
    else:
        story.append(Paragraph("No specific recommendations", normal_style))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Findings / Transcript:", heading_style))
    story.append(Paragraph(transcript_or_findings or "No additional findings recorded.", normal_style))

    story.append(Spacer(1, 40))
    footer_style = ParagraphStyle('FooterStyle', parent=normal_style, alignment=TA_CENTER, fontSize=8, textColor='gray')
    story.append(Paragraph("Generated by NEURAMED AI — Not for clinical use", footer_style))

    doc.build(story)

    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
