from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor


def _get_styles():
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'TitleStyle', parent=styles['Heading1'],
        fontName='Helvetica-Bold', fontSize=18,
        alignment=TA_CENTER, spaceAfter=20, textColor=HexColor('#003366')
    )
    heading_style = ParagraphStyle(
        'HeadingStyle', parent=styles['Heading2'],
        fontName='Helvetica-Bold', fontSize=13, spaceAfter=8,
        textColor=HexColor('#004488')
    )
    subheading_style = ParagraphStyle(
        'SubHeadingStyle', parent=styles['Heading3'],
        fontName='Helvetica-Bold', fontSize=11, spaceAfter=6,
        textColor=HexColor('#005599')
    )
    normal_style = styles['Normal']
    small_style = ParagraphStyle(
        'SmallStyle', parent=normal_style, fontSize=9
    )
    footer_style = ParagraphStyle(
        'FooterStyle', parent=normal_style,
        alignment=TA_CENTER, fontSize=8, textColor=HexColor('#999999')
    )
    return title_style, heading_style, subheading_style, normal_style, small_style, footer_style


def _add_header(story, session, title_style, normal_style):
    patient_code = session.patient.patient_code if session.patient else "WALK-IN"
    created_at_str = session.created_at.strftime("%Y-%m-%d %H:%M:%S") if session.created_at else "Unknown"
    agent_label = {"voice": "Voice Diagnosis", "imaging": "Imaging Analysis", "ocr": "OCR Report"}.get(session.agent_type, "Clinical Report")

    story.append(Paragraph("NEURAMED CLINICAL REPORT", title_style))
    story.append(Paragraph(f"<b>{agent_label.upper()}</b>", ParagraphStyle('AgentLabel', parent=normal_style, alignment=TA_CENTER, fontSize=12, textColor=HexColor('#006699'))))
    story.append(Spacer(1, 12))

    info_data = [
        ["Patient:", patient_code, "Date:", created_at_str],
        ["Agent:", session.agent_type.upper() if session.agent_type else "N/A",
         "Urgency:", (session.urgency_level or "N/A").upper()],
        ["Confidence:", f"{round((session.confidence_score or 0) * 100, 1)}%",
         "Processing:", f"{session.processing_time_ms or 0}ms"],
    ]
    info_table = Table(info_data, colWidths=[70, 150, 80, 150])
    info_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (2, 0), (2, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 16))


def _add_footer(story, footer_style):
    story.append(Spacer(1, 30))
    story.append(Paragraph("Generated by NEURAMED AI — Not for clinical use", footer_style))
    story.append(Paragraph("This report is AI-generated and should be reviewed by a qualified healthcare professional.", footer_style))


def generate_session_pdf(session) -> bytes:
    """Generate agent-specific PDF report. Returns raw PDF bytes."""
    if session.agent_type == "voice":
        return _generate_voice_pdf(session)
    elif session.agent_type == "imaging":
        return _generate_imaging_pdf(session)
    elif session.agent_type == "ocr":
        return _generate_ocr_pdf(session)
    return _generate_generic_pdf(session)


def _generate_voice_pdf(session) -> bytes:
    result_json = session.result_json or {}
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=36)
    title_style, heading_style, subheading_style, normal_style, small_style, footer_style = _get_styles()

    story = []
    _add_header(story, session, title_style, normal_style)

    # Urgency banner
    urg = (session.urgency_level or "medium").upper()
    urg_text = result_json.get("urgency_reasoning", f"Urgency level: {urg}")
    story.append(Paragraph(f"<b>URGENCY: {urg}</b> — {urg_text}", ParagraphStyle(
        'UrgBanner', parent=normal_style, fontSize=11,
        textColor=HexColor('#CC0000') if urg in ('CRITICAL', 'HIGH') else HexColor('#996600')
    )))
    story.append(Spacer(1, 12))

    # Differential Diagnosis
    story.append(Paragraph("DIFFERENTIAL DIAGNOSIS", heading_style))
    conditions = result_json.get("conditions", session.conditions_detected or [])
    for i, cond in enumerate(conditions):
        if isinstance(cond, dict):
            name = cond.get("name", "Unknown")
            prob = cond.get("probability", 0)
            icd = cond.get("icd_code", "")
            desc = cond.get("description", "")
            story.append(Paragraph(f"<b>{i+1}. {name}</b> — {round(prob*100)}% probability {f'(ICD-10: {icd})' if icd else ''}", normal_style))
            if desc:
                story.append(Paragraph(f"   {desc}", small_style))
            matching = cond.get("matching_symptoms", [])
            if matching:
                story.append(Paragraph(f"   Matching symptoms: {', '.join(matching)}", small_style))
            red_flags = cond.get("red_flags", [])
            if red_flags:
                story.append(Paragraph(f"   Red flags: {', '.join(red_flags)}", ParagraphStyle('RedFlag', parent=small_style, textColor=HexColor('#CC0000'))))
        else:
            story.append(Paragraph(f"&bull; {cond}", normal_style))
        story.append(Spacer(1, 6))

    # Differential summary
    diff_summary = result_json.get("differential_summary", "")
    if diff_summary:
        story.append(Spacer(1, 8))
        story.append(Paragraph("Clinical Reasoning", subheading_style))
        story.append(Paragraph(diff_summary, normal_style))

    story.append(Spacer(1, 12))

    # Recommended Tests
    tests = result_json.get("recommended_tests", [])
    if tests:
        story.append(Paragraph("RECOMMENDED TESTS", heading_style))
        for t in tests:
            if isinstance(t, dict):
                story.append(Paragraph(f"&bull; <b>{t.get('test', '')}</b> — {t.get('reason', '')}", normal_style))
            else:
                story.append(Paragraph(f"&bull; {t}", normal_style))
        story.append(Spacer(1, 12))

    # Immediate Actions
    actions = result_json.get("immediate_actions", result_json.get("recommendations", []))
    if actions:
        story.append(Paragraph("IMMEDIATE ACTIONS", heading_style))
        for i, a in enumerate(actions, 1):
            if isinstance(a, str):
                story.append(Paragraph(f"{i}. {a}", normal_style))
        story.append(Spacer(1, 12))

    # Medications to Avoid
    meds = result_json.get("medications_to_avoid", [])
    if meds:
        story.append(Paragraph("MEDICATIONS TO AVOID", heading_style))
        for m in meds:
            story.append(Paragraph(f"&bull; {m}", ParagraphStyle('MedWarn', parent=normal_style, textColor=HexColor('#CC0000'))))
        story.append(Spacer(1, 12))

    # When to go to ER
    er_text = result_json.get("when_to_go_to_er", "")
    if er_text:
        story.append(Paragraph("WHEN TO SEEK EMERGENCY CARE", heading_style))
        story.append(Paragraph(er_text, normal_style))
        story.append(Spacer(1, 12))

    # Follow-up
    follow_up = result_json.get("follow_up", "")
    if follow_up:
        story.append(Paragraph("FOLLOW-UP", heading_style))
        story.append(Paragraph(follow_up, normal_style))
        story.append(Spacer(1, 12))

    # Transcript
    story.append(Paragraph("PATIENT TRANSCRIPT", heading_style))
    story.append(Paragraph(session.input_summary or "No transcript recorded.", small_style))

    _add_footer(story, footer_style)
    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


def _generate_imaging_pdf(session) -> bytes:
    result_json = session.result_json or {}
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=36)
    title_style, heading_style, subheading_style, normal_style, small_style, footer_style = _get_styles()

    story = []
    _add_header(story, session, title_style, normal_style)

    # ACR Category
    acr = result_json.get("acr_category", "")
    acr_desc = result_json.get("acr_description", "")
    if acr:
        story.append(Paragraph(f"<b>ACR CLASSIFICATION: {acr}</b>", ParagraphStyle(
            'ACR', parent=normal_style, fontSize=13,
            textColor=HexColor('#CC0000') if '4' in acr or '5' in acr else HexColor('#006600')
        )))
        if acr_desc:
            story.append(Paragraph(acr_desc, small_style))
        story.append(Spacer(1, 12))

    # Primary Finding
    primary = result_json.get("primary_finding", "")
    if primary:
        story.append(Paragraph("PRIMARY FINDING", heading_style))
        story.append(Paragraph(primary, normal_style))
        story.append(Spacer(1, 12))

    # Findings
    findings = result_json.get("findings", "")
    if findings:
        story.append(Paragraph("RADIOLOGICAL FINDINGS", heading_style))
        story.append(Paragraph(findings, normal_style))
        story.append(Spacer(1, 8))

    impression = result_json.get("impression", "")
    if impression:
        story.append(Paragraph("IMPRESSION", heading_style))
        story.append(Paragraph(impression, normal_style))
        story.append(Spacer(1, 8))

    # Measurements & Distribution
    measurements = result_json.get("measurements", "")
    distribution = result_json.get("distribution", "")
    if measurements or distribution:
        story.append(Paragraph("MEASUREMENTS & DISTRIBUTION", heading_style))
        if measurements:
            story.append(Paragraph(f"<b>Size:</b> {measurements}", normal_style))
        if distribution:
            story.append(Paragraph(f"<b>Location:</b> {distribution}", normal_style))
        story.append(Spacer(1, 8))

    # Clinical Correlation
    cc = result_json.get("clinical_correlation", "")
    if cc:
        story.append(Paragraph("CLINICAL CORRELATION", heading_style))
        story.append(Paragraph(cc, normal_style))
        story.append(Spacer(1, 8))

    # Differential Diagnoses
    diffs = result_json.get("differential_diagnoses", [])
    if diffs:
        story.append(Paragraph("DIFFERENTIAL DIAGNOSES", heading_style))
        for d in diffs:
            story.append(Paragraph(f"&bull; {d}", normal_style))
        story.append(Spacer(1, 8))

    # Recommendations
    recs = result_json.get("recommendations", [])
    if recs:
        story.append(Paragraph("RECOMMENDATIONS", heading_style))
        for r in recs:
            if isinstance(r, dict):
                priority = r.get("priority", "routine").upper()
                action = r.get("action", "")
                story.append(Paragraph(f"[{priority}] {action}", normal_style))
            else:
                story.append(Paragraph(f"&bull; {r}", normal_style))
        story.append(Spacer(1, 8))

    # Follow-up Imaging
    fui = result_json.get("follow_up_imaging", result_json.get("follow_up", ""))
    if fui:
        story.append(Paragraph("FOLLOW-UP IMAGING", heading_style))
        story.append(Paragraph(fui, normal_style))

    _add_footer(story, footer_style)
    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


def _generate_ocr_pdf(session) -> bytes:
    result_json = session.result_json or {}
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=36)
    title_style, heading_style, subheading_style, normal_style, small_style, footer_style = _get_styles()

    story = []
    _add_header(story, session, title_style, normal_style)

    # Health Score
    health_score = result_json.get("overall_health_score", "")
    if health_score:
        color = {"good": '#006600', "fair": '#996600', "poor": '#CC6600', "critical": '#CC0000'}.get(health_score.lower(), '#333333')
        story.append(Paragraph(f"<b>OVERALL HEALTH ASSESSMENT: {health_score.upper()}</b>", ParagraphStyle(
            'HealthScore', parent=normal_style, fontSize=13, textColor=HexColor(color)
        )))
        story.append(Spacer(1, 8))

    # Critical Alerts
    alerts = result_json.get("critical_alerts", [])
    if alerts:
        story.append(Paragraph("CRITICAL ALERTS", heading_style))
        for a in alerts:
            story.append(Paragraph(f"⚠ {a}", ParagraphStyle('Alert', parent=normal_style, textColor=HexColor('#CC0000'))))
        story.append(Spacer(1, 12))

    # Summary
    summary = result_json.get("summary", "")
    if summary:
        story.append(Paragraph("EXECUTIVE SUMMARY", heading_style))
        story.append(Paragraph(summary, normal_style))
        story.append(Spacer(1, 12))

    # Abnormal Values
    abnormal = result_json.get("abnormal_values", [])
    if abnormal:
        story.append(Paragraph("ABNORMAL LAB VALUES", heading_style))
        table_data = [["Test", "Value", "Normal Range", "Severity"]]
        for v in abnormal:
            if isinstance(v, dict):
                table_data.append([
                    v.get("test", ""),
                    v.get("value", ""),
                    v.get("normal_range", ""),
                    v.get("severity", "").upper()
                ])
        if len(table_data) > 1:
            t = Table(table_data, colWidths=[120, 80, 100, 70])
            t.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#CCCCCC')),
                ('BACKGROUND', (0, 0), (-1, 0), HexColor('#E8E8E8')),
            ]))
            story.append(t)
        story.append(Spacer(1, 12))

    # Medications
    meds = result_json.get("medications", [])
    if meds:
        story.append(Paragraph("MEDICATIONS", heading_style))
        for m in meds:
            if isinstance(m, dict):
                story.append(Paragraph(
                    f"&bull; <b>{m.get('name', '')}</b> — {m.get('dose', '')} {m.get('frequency', '')} ({m.get('purpose', '')})",
                    normal_style
                ))
            else:
                story.append(Paragraph(f"&bull; {m}", normal_style))
        story.append(Spacer(1, 12))

    # Patient Action Items
    actions = result_json.get("patient_action_items", [])
    if actions:
        story.append(Paragraph("PATIENT ACTION ITEMS", heading_style))
        for i, a in enumerate(actions, 1):
            story.append(Paragraph(f"{i}. {a}", normal_style))
        story.append(Spacer(1, 12))

    # Follow-up
    followups = result_json.get("follow_up_instructions", [])
    if followups:
        story.append(Paragraph("FOLLOW-UP INSTRUCTIONS", heading_style))
        for f in followups:
            story.append(Paragraph(f"&bull; {f}", normal_style))

    _add_footer(story, footer_style)
    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


def _generate_generic_pdf(session) -> bytes:
    """Fallback for unknown agent types."""
    result_json = session.result_json or {}
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=36)
    title_style, heading_style, subheading_style, normal_style, small_style, footer_style = _get_styles()

    story = []
    _add_header(story, session, title_style, normal_style)

    story.append(Paragraph("Conditions Detected:", heading_style))
    if session.conditions_detected:
        for condition in session.conditions_detected:
            story.append(Paragraph(f"&bull; {condition}", normal_style))
    else:
        story.append(Paragraph("None detected", normal_style))

    recs = result_json.get("recommendations", [])
    if recs:
        story.append(Spacer(1, 12))
        story.append(Paragraph("Recommendations:", heading_style))
        for i, rec in enumerate(recs, 1):
            if isinstance(rec, str):
                story.append(Paragraph(f"{i}. {rec}", normal_style))

    _add_footer(story, footer_style)
    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
